### PR TITLE
Dispose of ThreadRental at conclusion of UITheory test

### LINKED ISSUE #44: Hanging UITheoryTestCase
Running tests in WinForms from command line hangs. These hangs do not happen when running tests from Visual Studio or via `dotnet test`. It looks like `UITheoryTestCase` doesn't get disposed.

I've isolated the hang to a standalone repo: https://github.com/weltkante/XUnitStaFactWinFormsHang

Opening a console and changing working directory to the build output, the (reduced) command line used to run the tests is: `dotnet exec --depsfile XUnitStaFactTest.deps.json --runtimeconfig XUnitStaFactTest.runtimeconfig.json "C:\Users\Tobias\.nuget\packages\xunit.runner.console/2.4.1/tools/netcoreapp2.0/xunit.console.dll" XUnitStaFactTest.dll -noautoreporters`

### PR DESCRIPTION
**Pull request by AArnott**
Fixes #44 hang at end of test run.

### CODE REVIEW

**Comment by AArnott** [comment]
@weltkante Would you review?

**Comment by weltkante** [comment]
I've started seeing following exception. Not sure if its related to this change. I doubt its related to the other change. (Also I'm not entirely sure if its a new issue or existed before and just wasn't surfacing due to the hang.)

```
Unhandled exception. System.InvalidOperationException: Invoke oder BeginInvoke kann für ein Steuerelement erst aufgerufen werden, wenn das Fensterhandle erstellt wurde.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous) in D:\projects\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Control.cs:line 6896
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args) in D:\projects\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Control.cs:line 4707
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Post(SendOrPostCallback d, Object state) in D:\projects\winforms\src\System.Windows.Forms\src\System\Windows\Forms\WindowsFormsSynchronizationContext.cs:line 90
   at Xunit.Sdk.Utilities.SyncContextAwaiter.OnCompleted(Action continuation)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitUnsafeOnCompleted[TAwaiter](TAwaiter& awaiter, IAsyncStateMachineBox box)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Process terminated. Assertion Failed
Marshaling control should have created its handle in its ctor.
   at System.Windows.Forms.WindowsFormsSynchronizationContext..ctor() in D:\projects\winforms\src\System.Windows.Forms\src\System\Windows\Forms\WindowsFormsSynchronizationContext.cs:line 35
   at System.Windows.Forms.WindowsFormsSynchronizationContext.InstallIfNeeded() in D:\projects\winforms\src\System.Windows.Forms\src\System\Windows\Forms\WindowsFormsSynchronizationContext.cs:line 143
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context) in D:\projects\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Application.ThreadContext.cs:line 1119
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context) in D:\projects\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Application.ThreadContext.cs:line 992
   at System.Windows.Forms.Application.DoEvents() in D:\projects\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Application.cs:line 811
   at Xunit.Sdk.WinFormsSynchronizationContextAdapter.PumpTill(SynchronizationContext synchronizationContext, Task task)
   at Xunit.Sdk.ThreadRental.<>c__DisplayClass11_0.<CreateAsync>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by weltkante** [comment]
Yeah can confirm this is not the fault of this PR, I rolled back to `1.0.31-beta` and skipped the hanging test assembly and I was already getting the same crash. Just never seen it before because the hanging test assembly runs before the crashing one.

**Comment by AArnott** [comment]
Thanks for testing. I trust you'll file another bug if you find the crash you saw is due to xunit.stafact.

**Comment by weltkante** [comment]
> if you find the crash you saw is due to xunit.stafact

Looks like this needs to be adressed in the WinForms unit tests, they are disposing the SC early. Probably shouldn't be WinFormsFacts if they setup/terminate the infrastructure manually.

**Comment by AArnott** [comment]
@weltkante I'm not sure whether you're blaming the `WinFormsFactAttribute` behavior or the unit tests in the WinForms repo. Can you clarify?

**Comment by weltkante** [comment]
Continuing discussion on dotnet/winforms#3297

**Pull request merged**
