### PR TITLE
Change all `Cocoa` references to `AppKit`

### PR DESCRIPTION
**Pull request by AArnott**
It turns out that "Cocoa" refers to the overall API, *including* "AppKit" which is the actual UI layer. By being precise in our naming here, if "Cocoa" or macOS ever move on to a new UI framework, maybe "Cocoa" will live on, but with the new UI libraries. We could support both, but not if both were called "Cocoa".

### CODE REVIEW

**Comment by AArnott** [comment]
@SiyuGithub do you have any concerns with this?

**Comment by SiyuGithub** [comment]
> 

It looks good to me. AppKit sounds like a better name in here. But since I am no longer work in the VSMac team, can we confirm this renaming with @sandyarmstrong too? Thanks.

**Comment by sandyarmstrong** [comment]
I don't think I agree with this. The UI thread concept is implemented in the Foundation layer (via `NSRunLoop`), not the AppKit layer. `CocoaFact` should work just as well with AppKit apps as it would with SwiftUI apps (if there were ever managed bindings for that). I think "Cocoa" is the most recognizable term that encompasses this.

**Comment by AArnott** [comment]
Great. Thanks for your insight. I'll close the PR.

**Pull request closed without merging**
