### PR TITLE
fix: StaTheory not supported in VS

### LINKED ISSUE #30: StaTheory is not supported in Visual Studio Runner
Example

```cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Collections.Generic;
using WinForms.Common.Tests;
using Xunit;

namespace System.Windows.Forms.Tests
{
    public class WebBrowserTests
    {
        public static IEnumerable<object[]> Parent_Set_TestData()
        {
           // yield return new object[] { null };
            yield return new object[] { new Control() };
        }

        [StaTheory]
        [MemberData(nameof(Parent_Set_TestData))]
        public void WebBrowser_Parent_Set_GetReturnsExpected(Control parent)
        {
            var browser = new WebBrowser
            {
                Parent = parent
            };
            Assert.Same(parent, browser.Parent);
            Assert.Null(browser.ActiveXInstance);
            Assert.False(browser.IsHandleCreated);
        }
    }
}
```

```
[9/23/2019 7:22:30.780 PM Informational] ---------- Discovery started ----------
[9/23/2019 7:22:33.339 PM Informational] [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1 (32-bit Desktop .NET 4.0.30319.42000)
[9/23/2019 7:22:34.552 PM Informational] [xUnit.net 00:00:01.26]   Discovering: WinformsTest
[9/23/2019 7:22:35.854 PM Informational] [xUnit.net 00:00:02.40]   Discovered:  WinformsTest
[9/23/2019 7:22:35.855 PM Informational] [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1 (32-bit Universal Windows)
[9/23/2019 7:22:36.060 PM Informational] ========== Discovery finished: 85 tests found (0:00:05.2286991) ==========
[9/23/2019 7:22:36.116 PM Informational] ---------- Run started ----------
[9/23/2019 7:22:38.520 PM Informational] [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1 (32-bit Desktop .NET 4.0.30319.42000)
[9/23/2019 7:22:40.388 PM Error] [xUnit.net 00:00:01.88] WinformsTest: Test case System.Windows.Forms.Tests.WebBrowserTests.WebBrowser_Parent_SetWithHandle_GetReturnsExpected failed to deserialize: Test case deserialization failure: System.InvalidOperationException: Could not de-serialize type 'Xunit.Sdk.UITheoryTestCase' because it lacks a parameterless constructor.
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue) in C:\Dev\xunit\xunit\src\common\XunitSerializationInfo.cs:line 213
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue) in C:\Dev\xunit\xunit\src\common\XunitSerializationInfo.cs:line 110
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 40
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 84
   at Xunit.Sdk.TestCaseBulkDeserializer.Deserialize(ITestFrameworkDiscoverer discoverer, ITestFrameworkExecutor executor, String serialization) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\TestCaseBulkDeserializer.cs:line 33
[9/23/2019 7:22:40.390 PM Error] [xUnit.net 00:00:01.88] WinformsTest: Test case System.Windows.Forms.Tests.WebBrowserTests.WebBrowser_Parent_Set_GetReturnsExpected failed to deserialize: Test case deserialization failure: System.InvalidOperationException: Could not de-serialize type 'Xunit.Sdk.UITheoryTestCase' because it lacks a parameterless constructor.
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue) in C:\Dev\xunit\xunit\src\common\XunitSerializationInfo.cs:line 213
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue) in C:\Dev\xunit\xunit\src\common\XunitSerializationInfo.cs:line 110
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 40
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 84
   at Xunit.Sdk.TestCaseBulkDeserializer.Deserialize(ITestFrameworkDiscoverer discoverer, ITestFrameworkExecutor executor, String serialization) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\TestCaseBulkDeserializer.cs:line 33
[9/23/2019 7:22:40.416 PM Informational] [xUnit.net 00:00:01.89]   Starting:    WinformsTest
[9/23/2019 7:22:47.282 PM Informational] [xUnit.net 00:00:08.77]   Finished:    WinformsTest
[9/23/2019 7:22:47.807 PM Informational] ========== Run finished: 628 tests run (0:00:11.4979809) ==========
```

### PR DESCRIPTION
**Pull request by RussKie**
The following test would not be executable:

    public class WebBrowserTests
    {
        public static IEnumerable<object[]> TestData()
        {
            yield return new object[] { null };
            yield return new object[] { new object() };
        }

        [StaTheory]
        [MemberData(nameof(TestData))]
        public void TheoryTest(object parent)
        {
            Assert.Null(parent);
        }
    }

The error message indicates that the test cannot be deserialised:

	Test case WebBrowserTests failed to deserialize: Test case deserialization failure: System.InvalidOperationException: Could not de-serialize type 'Xunit.Sdk.UITheoryTestCase' because it lacks a parameterless constructor.
	   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue)
	   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue)
	   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue)
	   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value)
	   at Xunit.Sdk.TestCaseBulkDeserializer.Deserialize(ITestFrameworkDiscoverer discoverer, ITestFrameworkExecutor executor, String serialization)

Add serialisation plumbing to fix the issue.

Fixes #30

I've tested the fix on the WinForms repo, and I was able to run all tests.

### CODE REVIEW

**Comment by RussKie** [comment]
@AArnott is there anything blocking this from being merged? The issue is blocking us at WinForms

**Comment by AArnott** [comment]
Just that this was "read" on my mobile device so it didn't come up on my main computer. I'm looking at it now.

IIRC though, I never saw a repro of this and I'd like to see it in order to validate that this change fixes it. Any pointers on how to repro?

**Comment by AArnott** [comment]
This will be on nuget.org imminently as 1.0.19-beta.

Per #35 though, any subsequent version of this package will likely *remove* .NET Core 3.0 WPF/WinForms support altogether in favor of a separate package that delivers similar functionality.

**Comment by RussKie** [comment]
> Any pointers on how to repro?

Sure, easy

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" />
    <PackageReference Include="coverlet.collector" Version="1.0.1" />
    <PackageReference Include="Xunit.StaFact" Version="0.3.18" />
  </ItemGroup>

</Project>
```

```cs
// Class1.cs

using System.Collections.Generic;
using Xunit;

namespace StaFactRepro
{
    public class WebBrowserTests
    {

        [Fact]
        public void Test()
        {
            Assert.Null(null);
        }

        public static IEnumerable<object[]> TestData()
        {
            yield return new object[] { null };
            yield return new object[] { new object() };
        }

        [StaTheory]
        [MemberData(nameof(TestData))]
        public void TheoryTest(object parent)
        {
            Assert.Null(parent);
        }
    }
}
```

Run tests and observe the issue in the Tests console:
```
  </GoogleTestAdapterSettings>
</RunSettings>.
[12/12/2019 11:56:51.134 AM] Trying to update view -2053683634
[12/12/2019 11:56:51.134 AM] Updating view -2053683634
[12/12/2019 11:56:51.136 AM] Updating view -2053683634
[12/12/2019 11:56:51.140 AM] UpdateSummary Detail Unchanged: SKIPPED
[12/12/2019 11:56:51.399 AM] UpdateSummary Detail Unchanged: SKIPPED
[12/12/2019 11:56:51.563 AM] [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1 (64-bit .NET Core 3.1.0-preview3.19553.2)
[12/12/2019 11:56:52.133 AM] [xUnit.net 00:00:00.58] StaFactRepro: Catastrophic error during deserialization: System.InvalidOperationException: Could not de-serialize type 'Xunit.Sdk.UITheoryTestCase' because it lacks a parameterless constructor.
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue) in C:\Dev\xunit\xunit\src\common\XunitSerializationInfo.cs:line 213
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue) in C:\Dev\xunit\xunit\src\common\XunitSerializationInfo.cs:line 110
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 40
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 84
   at Xunit.DefaultTestCaseBulkDeserializer.<BulkDeserialize>b__2_0(String serialization) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Descriptor\DefaultTestCaseBulkDeserializer.cs:line 22
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Xunit.DefaultTestCaseBulkDeserializer.BulkDeserialize(List`1 serializations) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Descriptor\DefaultTestCaseBulkDeserializer.cs:line 22
   at Xunit.Xunit2.BulkDeserialize(List`1 serializations) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2.cs:line 75
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 562
[12/12/2019 11:56:52.143 AM] [xUnit.net 00:00:00.59]   Starting:    StaFactRepro
[12/12/2019 11:56:52.182 AM] [xUnit.net 00:00:00.63]   Finished:    StaFactRepro
[12/12/2019 11:56:52.295 AM] ========== Run finished: 0 tests run (0:00:01.5412387) ==========
[12/12/2019 11:56:52.603 AM] Trying to update view -2053683634
[12/12/2019 11:56:52.603 AM] Updating view -2053683634
[12/12/2019 11:56:52.605 AM] Updating view -2053683634
[12/12/2019 11:56:52.617 AM] UpdateSummary Detail Unchanged: SKIPPED
[12/12/2019 11:56:52.983 AM] UpdateSummary Detail Unchanged: SKIPPED
```

**Pull request merged**
