### PR TITLE
Move .NET Core 3.0 WPF/WinForms support into its own package

### LINKED ISSUE #35: WPF support on .NET Core 3.0 breaks .NET Core 3.0 consumers on Linux/Mac
The mere presence of WPF support on .NET Core 3.0 for this package injects artifacts into the package nuspec file that breaks the build for anyone depending on this package and building on mac/linux and targeting .NET Core 3.0. Even though they don't care about WPF, the dependency breaks the build.

See https://github.com/dotnet/sdk/issues/3592

We'll need to break up WPF support on .NET Core 3.0 into its own package, evidently. :(

### PR DESCRIPTION
**Pull request by AArnott**
.NET Core 3.0's design for WPF/WinForms requires that a NuGet package that supports WPF/WinForms on .NET Core 3.0 can only be installed to a Windows-targeted project and cannot be restored or built on another operating system. Since we both want to support WPF/WinForms on .NET Core 3.0 as well as continue to support Xunit.StaFact being used on non-Windows operating systems, we have to split the package in two.

Fixes #35

### CODE REVIEW

**Comment by AArnott** [comment]
@RussKie @hughbe I would very much appreciate your validation of this change given your past struggles and feedback regarding the ability to run tests in various environments. 

To validate, can you please:
1. Add https://pkgs.dev.azure.com/andrewarnott/OSS/_packaging/PublicCI/nuget/v3/index.json as a package source
1. For .NET Core 3.0 WPF/WinForms:
   ```
   Uninstall-Package Xunit.StaFact
   Install-Package Xunit.StaFact.NetCoreWindowsDesktop -Version 1.0.21-beta-ga7946eb0b8
   ```
   Or for all other use cases:
   ```
   Update-Package Xunit.StaFact -Version 1.0.21-beta-ga7946eb0b8
   ```
1. Run all tests in each environment (e.g. command line, CI build, Test Explorer) and verify that all tests are discovered and execute as expected.

Can you please confirm here that it works for you?

**Comment by RussKie** [comment]
Using the repro provided in https://github.com/AArnott/Xunit.StaFact/pull/37#issuecomment-564801627

* Fails using the old Xunit.StaFact.
* Succeeds using the new Xunit.StaFact
* Succeeds using the new Xunit.StaFact.NetCoreWindowsDesktop

**Comment by RussKie** [comment]
However testing it in dotnet/winforms - and it breaks the build in a horrible way...

1. clone https://github.com/dotnet/winforms/compare/dev/test/Xunit.StaFact.NetCoreWindowsDesktop
2. from a cli run `build`
3. observe errors

I have nuked all xunit-related packages from my <user>/packages/.nuget folder, nuked the winforms/artifacts folder to no avail...
Revert the commit, and everything just builds 😕

**Comment by AArnott** [comment]
Thanks for testing, @RussKie.

> Revert the commit, and everything just builds

What exactly are you reverting to when it works? The 1.0.19-beta release or something earlier than that?

Your 42.42.42.42 version of WinForms doesn't look like something customers would see. That's some bizarre assembly version due to you using a private build of WinForms, yes? If so, I don't know how I can accommodate that any better (but I'm open to ideas), nor do I know why 1.0.19-beta would work better than the 1.0.21-beta that I asked you to try since they both build their WinForms dependency the same way, I think.

**Comment by RussKie** [comment]
> What exactly are you reverting to when it works?

I'm reverting to the previous commit, which is 5d79f3e58f6ef8359aab26ee3535c7c11a343892


I'll try it on a clean VM in coming days, but if I can't run it on my dev machine I can't use the new lib...
I'm quite puzzled why it is failing after the update, but there must be some sort of a redirect is (or isn't) failing

**Pull request closed without merging**
